########################################################################
#  Radioastronomic Spectrometer
#  Computational core for IBM Cell Broadband Engine, SPE core unit
#
#  Uses the AMD Core Math Library
#
#  (C) 2008 Jan Wagner
#      Licensed according to GNU GPL
########################################################################


# TODO !

# http://developer.amd.com/acml.jsp

BITS_PROCESSOR := 64
