# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt4designer.ui'
#
# Created: Fri Jan 15 13:31:07 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 350)
        Dialog.setMinimumSize(QtCore.QSize(608, 350))
        Dialog.setMaximumSize(QtCore.QSize(608, 350))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 301))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabProcessing = QtGui.QWidget()
        self.tabProcessing.setObjectName("tabProcessing")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabProcessing)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 571, 271))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtINITemplate = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.txtINITemplate.setObjectName("txtINITemplate")
        self.horizontalLayout.addWidget(self.txtINITemplate)
        self.cmdSelectINI = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.cmdSelectINI.setObjectName("cmdSelectINI")
        self.horizontalLayout.addWidget(self.cmdSelectINI)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtInputFile1 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.txtInputFile1.setObjectName("txtInputFile1")
        self.horizontalLayout_5.addWidget(self.txtInputFile1)
        self.cmdSelectFile1 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.cmdSelectFile1.setObjectName("cmdSelectFile1")
        self.horizontalLayout_5.addWidget(self.cmdSelectFile1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txtInputFile2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.txtInputFile2.setObjectName("txtInputFile2")
        self.horizontalLayout_6.addWidget(self.txtInputFile2)
        self.cmdSelectFile2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.cmdSelectFile2.setObjectName("cmdSelectFile2")
        self.horizontalLayout_6.addWidget(self.cmdSelectFile2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 8, 0, 1, 1)
        self.txtOutputFile1 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.txtOutputFile1.setObjectName("txtOutputFile1")
        self.gridLayout_2.addWidget(self.txtOutputFile1, 8, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 9, 0, 1, 1)
        self.txtOutputINI = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.txtOutputINI.setObjectName("txtOutputINI")
        self.gridLayout_2.addWidget(self.txtOutputINI, 9, 2, 1, 1)
        self.line_10 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 8, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.spinChannelFile1 = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.spinChannelFile1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinChannelFile1.setMinimum(1)
        self.spinChannelFile1.setMaximum(32)
        self.spinChannelFile1.setObjectName("spinChannelFile1")
        self.gridLayout_2.addWidget(self.spinChannelFile1, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.spinChannelFile2 = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.spinChannelFile2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinChannelFile2.setMinimum(1)
        self.spinChannelFile2.setMaximum(32)
        self.spinChannelFile2.setObjectName("spinChannelFile2")
        self.gridLayout_2.addWidget(self.spinChannelFile2, 6, 2, 1, 1)
        self.line_12 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 7, 2, 1, 1)
        self.line_13 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 7, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_2.addWidget(self.line_14, 1, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_2.addWidget(self.line_15, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabProcessing, "")
        self.tabInputFormat = QtGui.QWidget()
        self.tabInputFormat.setObjectName("tabInputFormat")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tabInputFormat)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 571, 225))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.cmbSourceFormat = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.cmbSourceFormat.setObjectName("cmbSourceFormat")
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.cmbSourceFormat.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.cmbSourceFormat, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.cmbSourceChannels = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.cmbSourceChannels.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmbSourceChannels.setObjectName("cmbSourceChannels")
        self.cmbSourceChannels.addItem(QtCore.QString())
        self.cmbSourceChannels.addItem(QtCore.QString())
        self.cmbSourceChannels.addItem(QtCore.QString())
        self.cmbSourceChannels.addItem(QtCore.QString())
        self.cmbSourceChannels.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.cmbSourceChannels, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.cmbBitsPerSample = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.cmbBitsPerSample.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmbBitsPerSample.setObjectName("cmbBitsPerSample")
        self.cmbBitsPerSample.addItem(QtCore.QString())
        self.cmbBitsPerSample.addItem(QtCore.QString())
        self.cmbBitsPerSample.addItem(QtCore.QString())
        self.cmbBitsPerSample.addItem(QtCore.QString())
        self.cmbBitsPerSample.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.cmbBitsPerSample, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.txtBandwidth = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.txtBandwidth.setObjectName("txtBandwidth")
        self.gridLayout_3.addWidget(self.txtBandwidth, 3, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 4, 0, 1, 1)
        self.txtPCalHarmonicsHz = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.txtPCalHarmonicsHz.setObjectName("txtPCalHarmonicsHz")
        self.gridLayout_3.addWidget(self.txtPCalHarmonicsHz, 4, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 5, 0, 1, 1)
        self.txtPCalOffset = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.txtPCalOffset.setObjectName("txtPCalOffset")
        self.gridLayout_3.addWidget(self.txtPCalOffset, 5, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 2, 1, 1)
        self.txtSkipSeconds = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.txtSkipSeconds.setObjectName("txtSkipSeconds")
        self.gridLayout_3.addWidget(self.txtSkipSeconds, 6, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabInputFormat, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 571, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.txtFFTPoints = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.txtFFTPoints.setObjectName("txtFFTPoints")
        self.gridLayout_4.addWidget(self.txtFFTPoints, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.txtFFTIntegrationTimeSec = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.txtFFTIntegrationTimeSec.setObjectName("txtFFTIntegrationTimeSec")
        self.gridLayout_4.addWidget(self.txtFFTIntegrationTimeSec, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinFFTOverlapFactor = QtGui.QSpinBox(self.gridLayoutWidget_4)
        self.spinFFTOverlapFactor.setMinimum(1)
        self.spinFFTOverlapFactor.setMaximum(10)
        self.spinFFTOverlapFactor.setProperty("value", QtCore.QVariant(2))
        self.spinFFTOverlapFactor.setObjectName("spinFFTOverlapFactor")
        self.gridLayout_4.addWidget(self.spinFFTOverlapFactor, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 3, 0, 1, 1)
        self.cmbFFTWindowing = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.cmbFFTWindowing.setObjectName("cmbFFTWindowing")
        self.cmbFFTWindowing.addItem(QtCore.QString())
        self.cmbFFTWindowing.addItem(QtCore.QString())
        self.cmbFFTWindowing.addItem(QtCore.QString())
        self.cmbFFTWindowing.addItem(QtCore.QString())
        self.cmbFFTWindowing.addItem(QtCore.QString())
        self.cmbFFTWindowing.addItem(QtCore.QString())
        self.gridLayout_4.addWidget(self.cmbFFTWindowing, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tabOutput = QtGui.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tabOutput)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 571, 191))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.cmbOutputFormat = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmbOutputFormat.setObjectName("cmbOutputFormat")
        self.cmbOutputFormat.addItem(QtCore.QString())
        self.cmbOutputFormat.addItem(QtCore.QString())
        self.gridLayout_5.addWidget(self.cmbOutputFormat, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.chkPCal = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.chkPCal.setObjectName("chkPCal")
        self.gridLayout_5.addWidget(self.chkPCal, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.chkCrossPol = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.chkCrossPol.setObjectName("chkCrossPol")
        self.gridLayout_5.addWidget(self.chkCrossPol, 2, 1, 1, 1)
        self.chkPlotting = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.chkPlotting.setEnabled(True)
        self.chkPlotting.setObjectName("chkPlotting")
        self.gridLayout_5.addWidget(self.chkPlotting, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 0, 1, 1)
        self.chkLog = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.chkLog.setObjectName("chkLog")
        self.gridLayout_5.addWidget(self.chkLog, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LogInputFile = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.LogInputFile.setObjectName("LogInputFile")
        self.horizontalLayout_7.addWidget(self.LogInputFile)
        self.cmdSelectLogFile = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.cmdSelectLogFile.setObjectName("cmdSelectLogFile")
        self.horizontalLayout_7.addWidget(self.cmdSelectLogFile)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tabOutput, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 1, 0, 1, 1)
        self.spinNumCPUCores = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinNumCPUCores.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinNumCPUCores.setMinimum(1)
        self.spinNumCPUCores.setMaximum(8)
        self.spinNumCPUCores.setObjectName("spinNumCPUCores")
        self.gridLayout.addWidget(self.spinNumCPUCores, 1, 1, 1, 1)
        self.spinMaxBufSize = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinMaxBufSize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinMaxBufSize.setMinimum(8)
        self.spinMaxBufSize.setMaximum(512)
        self.spinMaxBufSize.setSingleStep(8)
        self.spinMaxBufSize.setProperty("value", QtCore.QVariant(128))
        self.spinMaxBufSize.setObjectName("spinMaxBufSize")
        self.gridLayout.addWidget(self.spinMaxBufSize, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(132, 310, 461, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmdProcess = QtGui.QPushButton(self.layoutWidget)
        self.cmdProcess.setFlat(False)
        self.cmdProcess.setObjectName("cmdProcess")
        self.horizontalLayout_4.addWidget(self.cmdProcess)
        self.cmdCancel = QtGui.QPushButton(self.layoutWidget)
        self.cmdCancel.setFlat(False)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout_4.addWidget(self.cmdCancel)
        self.cmdQuit = QtGui.QPushButton(self.layoutWidget)
        self.cmdQuit.setAutoDefault(True)
        self.cmdQuit.setObjectName("cmdQuit")
        self.horizontalLayout_4.addWidget(self.cmdQuit)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "SWSpectrometer GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "Template INI file:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtINITemplate.setToolTip(QtGui.QApplication.translate("Dialog", "Location of an example or template INI file from which to load settings into this program.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSelectINI.setToolTip(QtGui.QApplication.translate("Dialog", "Select INI file and load settings into this program.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSelectINI.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Input sample file #1:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtInputFile1.setToolTip(QtGui.QApplication.translate("Dialog", "The first raw input data file to use. Required.", None, QtGui.QApplication.UnicodeUTF8))
        self.txtInputFile1.setText(QtGui.QApplication.translate("Dialog", "scan001.pcevn", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSelectFile1.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.txtInputFile2.setToolTip(QtGui.QApplication.translate("Dialog", "The second raw input data file to use. \n"
"\n"
"Optional, unless output options contain cross-polarisation.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSelectFile2.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Input sample file #2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Output spectrum file #1:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtOutputFile1.setText(QtGui.QApplication.translate("Dialog", "scan001.pcevn.spec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog", "Output INI file:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtOutputINI.setText(QtGui.QApplication.translate("Dialog", "scan001.pcevn.spec.ini", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Channel from file#1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Channel from file#2:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProcessing), QtGui.QApplication.translate("Dialog", "Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Source format:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(0, QtGui.QApplication.translate("Dialog", "RawSigned", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(1, QtGui.QApplication.translate("Dialog", "RawUnsigned", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(2, QtGui.QApplication.translate("Dialog", "VLBA1_4-128-4-2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(3, QtGui.QApplication.translate("Dialog", "VLBA1_4-128-8-1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(4, QtGui.QApplication.translate("Dialog", "VLBA1_2-128-8-2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(5, QtGui.QApplication.translate("Dialog", "MkIV1_4-128-4-2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(6, QtGui.QApplication.translate("Dialog", "MkIV1_4-128-8-2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(7, QtGui.QApplication.translate("Dialog", "MkIV1_2-128-8-2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(8, QtGui.QApplication.translate("Dialog", "MkIV1_2-256-8-2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(9, QtGui.QApplication.translate("Dialog", "Mark5B", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(10, QtGui.QApplication.translate("Dialog", "VDIF", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(11, QtGui.QApplication.translate("Dialog", "iBOB", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceFormat.setItemText(12, QtGui.QApplication.translate("Dialog", "Maxim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Number of channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceChannels.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceChannels.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceChannels.setItemText(2, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceChannels.setItemText(3, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSourceChannels.setItemText(4, QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Bits per sample:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBitsPerSample.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBitsPerSample.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBitsPerSample.setItemText(2, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBitsPerSample.setItemText(3, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBitsPerSample.setItemText(4, QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Analog bandwidth:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtBandwidth.setText(QtGui.QApplication.translate("Dialog", "8e6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "Phase cal comb spacing:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtPCalHarmonicsHz.setText(QtGui.QApplication.translate("Dialog", "1e6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Phase cal offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtPCalOffset.setText(QtGui.QApplication.translate("Dialog", "10e3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Hz from DC", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSkipSeconds.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Input seconds to skip:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInputFormat), QtGui.QApplication.translate("Dialog", "Input File Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "DFT points:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFFTPoints.setText(QtGui.QApplication.translate("Dialog", "160e3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "DFT integration time:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFFTIntegrationTimeSec.setText(QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "DFT overlap factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "DFT window function:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFFTWindowing.setItemText(0, QtGui.QApplication.translate("Dialog", "Cosine2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFFTWindowing.setItemText(1, QtGui.QApplication.translate("Dialog", "Cosine", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFFTWindowing.setItemText(2, QtGui.QApplication.translate("Dialog", "Hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFFTWindowing.setItemText(3, QtGui.QApplication.translate("Dialog", "Hann", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFFTWindowing.setItemText(4, QtGui.QApplication.translate("Dialog", "Blackman", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFFTWindowing.setItemText(5, QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "(100/N)%", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Spectrum Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Output Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOutputFormat.setItemText(0, QtGui.QApplication.translate("Dialog", "Binary", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOutputFormat.setItemText(1, QtGui.QApplication.translate("Dialog", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Phase cal:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPCal.setText(QtGui.QApplication.translate("Dialog", "extract phase calibration signal phases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Correlation:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCrossPol.setText(QtGui.QApplication.translate("Dialog", "calculate cross-correlation between file#1 and file#2 data", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlotting.setText(QtGui.QApplication.translate("Dialog", "plot each integrated spectrum to show live progress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Enable plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLog.setText(QtGui.QApplication.translate("Dialog", " enable log output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Output log:", None, QtGui.QApplication.UnicodeUTF8))
        self.LogInputFile.setToolTip(QtGui.QApplication.translate("Dialog", "The second raw input data file to use. \n"
"\n"
"Optional, unless output options contain cross-polarisation.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSelectLogFile.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Log file name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), QtGui.QApplication.translate("Dialog", "Output Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "Maximum buffer size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog", "Number of threads:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdProcess.setText(QtGui.QApplication.translate("Dialog", "Process!", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdQuit.setText(QtGui.QApplication.translate("Dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))

